### ISSUE TITLE
Parameter are not properly translated with IonQ gates

### ISSUE THREAD

**Issue by jcjaskula-aws** [qiskit-community/qiskit-braket-provider#151] opened 2024-02-10 03:56 UTC
### Steps to reproduce the problem
```
from braket.circuits import Circuit
from qiskit_braket_provider.providers.adapter import to_braket, to_qiskit
c=Circuit().gpi2(1, FreeParameter("phi"))
qc=to_qiskit(c)
print(qc)
print(c)
```

```
        ┌───────────┐ ░ ┌─┐
     q: ┤ Gpi2(phi) ├─░─┤M├
        └───────────┘ ░ └╥┘
meas: 1/═════════════════╩═
                         0 
```
```
T  : |    0    |
                
q1 : -GPi2(phi)-

T  : |    0    |

Unassigned parameters: [phi].
````

### What is the current behavior?
Qiskit circuit has `GPi2(phi)`.

### What is the expected behavior?
Qiskit circuit should have `GPi2(phi/2/pi)`.

**Comment by speller26** [comment] 2024-02-10 10:34
The problem is coming from these lines:
https://github.com/qiskit-community/qiskit-braket-provider/blob/3be09a76169147cc29e7434e7851b137f38e6ea8/qiskit_braket_provider/providers/adapter.py#L525-L528
The Qiskit gate's parameter expressions are being replaced entirely by the new parameter being created in `to_qiskit`
https://github.com/qiskit-community/qiskit-braket-provider/blob/3be09a76169147cc29e7434e7851b137f38e6ea8/qiskit_braket_provider/providers/adapter.py#L497-L500
when it should be the _variables_ that get reassigned.

**Closed** 2024-02-12 08:15 UTC
Labels: bug
