### ISSUE TITLE
Problem in transpiling circuit with Qiskit on Rigetti-M3

### ISSUE THREAD

**Issue by bgupt** [qiskit-community/qiskit-braket-provider#80] opened 2023-03-26 01:53 UTC
### Steps to reproduce the problem
```
from qiskit.algorithms import VQE from qiskit.opflow import (
I, X, Z,
)
from qiskit import transpile, QuantumCircuit from qiskit.circuit.random import random_circuit from qiskit.visualization import plot_histogram from qiskit.algorithms.optimizers import SLSQP from qiskit.circuit.library import TwoLocal
from qiskit.utils import QuantumInstance
from braket.aws import AwsQuantumJob import qiskit_braket_provider
from qiskit_braket_provider import AWSBraketProvider, BraketLocalBackend

from qiskit.algorithms import QAOA

from qiskit.opflow.primitive_ops import PauliOp

p =10
provider = AWSBraketProvider() backend = QuantumInstance(
provider.get_backend("Aspen-M-3"),
shots=1024, )
qaoa = QAOA( reps=p,
quantum_instance=backend, )
op = PauliOp(Pauli("ZZ"))
qaoa = QAOA()
ckt = qaoa.construct_circuit([1.0, 1.5],op)

transpiled_circuit = transpile(
    ckt[0], 
    backend=provider.get_backend("Aspen-M-3"), 
    #seed_transpiler=42
)
transpiled_circuit.draw(idle_wires=False, fold=-1)
```

### What is the current behavior?
Transpiling a quantum circuit with qiskit-braket fails on Rigetti M3. The problem has only been seen with Rigetti so far and not with IONQ and Lucy. See the attached PDF. 
[PFR Mar 12, 2023.pdf](https://github.com/qiskit-community/qiskit-braket-provider/files/11070576/PFR.Mar.12.2023.pdf)

### What is the expected behavior?
Transpiling is expected to complete without error on all devices.

**Comment by christianbmadsen** [comment] 2023-04-13 15:22
Thank you for raising this. @bgupt I believe this is a duplicate of the existing issue https://github.com/qiskit-community/qiskit-braket-provider/issues/50.

**Closed by christianbmadsen** 2023-04-13 15:22 UTC
Labels: bug
